# Generated by Django 3.0.8 on 2020-07-31 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('crm', models.IntegerField(default='')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponivel', models.BooleanField(default=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Agenda')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Horario')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(through='clinica.HorarioAgenda', to='clinica.Horario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Medico'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(check=models.Q(dia__gte=datetime.datetime(2020, 7, 31, 3, 0, 13, 499593, tzinfo=utc)), name='dia_lte'),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia')},
        ),
    ]
