# Generated by Django 3.1 on 2020-08-09 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'especialidade',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('crm', models.IntegerField(default='')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidade')),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='HorarioAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponivel', models.BooleanField(default=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.agenda')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.horario')),
            ],
            options={
                'db_table': 'horario_agenda',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('horario_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.horarioagenda')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(through='clinica.HorarioAgenda', to='clinica.Horario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.medico'),
        ),
    ]
