# Generated by Django 3.0.8 on 2020-07-31 03:00

from django.db import migrations
import datetime

def insert_horarios(apps, schema_editor):    
    Horario = apps.get_model('clinica', 'Horario')
    for h in [{'hora': 8, 'minuto': 15},{'hora': 8, 'minuto': 30},{'hora': 8, 'minuto': 45},{'hora': 9, 'minuto': 0},{'hora': 9, 'minuto': 15},{'hora': 9, 'minuto': 30},{'hora': 9, 'minuto': 45},{'hora': 10, 'minuto': 0},{'hora': 10, 'minuto': 15},{'hora': 10, 'minuto': 30},{'hora': 10, 'minuto': 45},{'hora': 11, 'minuto': 0},{'hora': 11, 'minuto': 15},{'hora': 11, 'minuto': 30},{'hora': 11, 'minuto': 45},{'hora': 12, 'minuto': 0},{'hora': 12, 'minuto': 15},{'hora': 12, 'minuto': 30},{'hora': 12, 'minuto': 45},{'hora': 13, 'minuto': 0},{'hora': 13, 'minuto': 15},{'hora': 13, 'minuto': 30},{'hora': 13, 'minuto': 45},{'hora': 14, 'minuto': 0},{'hora': 14, 'minuto': 15},{'hora': 14, 'minuto': 30},{'hora': 14, 'minuto': 45},{'hora': 15, 'minuto': 0},{'hora': 15, 'minuto': 15},{'hora': 15, 'minuto': 30},{'hora': 15, 'minuto': 45},{'hora': 16, 'minuto': 0},{'hora': 16, 'minuto': 15},{'hora': 16, 'minuto': 30},{'hora': 16, 'minuto': 45},{'hora': 17, 'minuto': 0},{'hora': 17, 'minuto': 15},{'hora': 17, 'minuto': 30},{'hora': 17, 'minuto': 45},{'hora': 18, 'minuto': 0},{'hora': 18, 'minuto': 15},{'hora': 18, 'minuto': 30},{'hora': 18, 'minuto': 45},{'hora': 19, 'minuto': 0},{'hora': 19, 'minuto': 15},{'hora': 19, 'minuto': 30},{'hora': 19, 'minuto': 45},{'hora': 20, 'minuto': 0}]:
        horario = Horario(hora = datetime.time(h['hora'],h['minuto']))
        horario.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_horarios),
    ]
