# Generated by Django 3.1 on 2020-08-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_seed_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='horario_agenda',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.AddField(
            model_name='consulta',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.agenda'),
        ),
    ]
