# Generated by Django 3.1 on 2020-08-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_consulta_horario_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='horario_agenda',
        ),
        migrations.AddField(
            model_name='consulta',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.horario'),
        ),
    ]
