# Generated by Django 3.1 on 2020-08-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20200818_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='horario',
        ),
        migrations.AddField(
            model_name='consulta',
            name='horario_agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.horarioagenda'),
        ),
    ]
